HW4
KaterynaHruvman/nodejs-homework-REST-API-NODE pull request #3
Opened 2021-09-21 21:01 UTC by KaterynaHruvman

2021-09-21 22:29 UTC, Danil44 requested changes

2021-09-21 22:29 UTC, Danil44 commented on src/middlwarer/authMiddleware.js
> +    if (userExist.token !== token) {
Умови можна з'єднати в одну використовуючи || оператор

2021-09-21 22:29 UTC, Danil44 commented on src/model/user.js
> +  // await user.save()
—

2021-09-21 22:29 UTC, Danil44 commented on src/model/user.js
> +  // if (await bcrypt.compare(password, user.password)) {
—

2021-09-21 22:29 UTC, Danil44 commented on src/model/user.js
> +  if (!(password === user.password)) {
!==

2021-09-21 22:29 UTC, Danil44 commented on src/model/user.js
> +  if (!logoutUser) {
спочатку потрібно знайти юзера, перевірити, і вже потім робити апдейт

2021-09-21 22:29 UTC, Danil44 commented on src/model/user.js
> +  if (!updateUserSubscription) {
Та ж сама ситуація і тут

2021-09-22 09:57 UTC, KaterynaHruvman commented on src/model/user.js
> +  if (!logoutUser) {
треба выкористати не метод findOneAndUpdate, а просто  findOne? Так?

2021-09-23 18:22 UTC, KaterynaHruvman commented
Посмотрите правки

2021-09-23 21:35 UTC, Danil44 approved these changes

2021-09-24 04:17 UTC, merged